#EL MANEJO DE ERRORES A TRAVÉS DE TRY- EXCEPT BUSCA QUE EL PROGRAMA NO SE CAIGA AUNQEU TENGA ERRORES.
#EL CÓDIGO RIESGOSO VA DENTRO DEL TRY IDENTADO Y EN EL EXCEPT, LO QUE SE QUIERE QUE SE EJECUTE CUANDO 
#EXISTA EL ERROR.

#PARA OBTENER EL ERROR SE ESCRIBE EL EXCEPTION AS 'NOMBRE DE VARIABLE', EN ESTE CASO 'e'. 

cadena = 'Hola'
try:
    x = int(cadena)
except Exception as e:
    print('Ha habido un error', e)


print('He llegado al final')